### ISSUE TITLE
The included 64-bit build(kernel8-5.4.81-rt.tgz) in release rt kernel 5.4.81-rt45 for Raspberry Pi is not RT

### ISSUE THREAD

**Issue by kwang-12** [kdoren/linux#1]
As the title stated, I downloaded the compiled kernel to my Raspberry Pi 4b (8gb RAM) and did the following:
`tar xzf kernel8-5.4.81-rt.tgz`
`cd boot`
`sudo cp -rd * /boot/`
`cd ../broadcom`
`sudo cp -rd * /boot/`
`cd ../lib`
`sudo cp -rd * /lib/`
`cd ../overlays`
`sudo cp -rd * /boot/overlays`
Then added the following in /boot/config.txt and reboot.
```
arm_64bit=1
kernel=kernel8_rt.img
```
`uname -a` returns the following:
`Linux raspberrypi 5.4.81-rt45-v8+ #4 SMP PREEMPT Sat Dec 12 04:48:41 PST 2020 aarch64 GNU/Linux`

It seems that the Preempt_RT was not selected before compile...

**Comment by kdoren** [comment]
You are correct, sorry about that.  I somehow built it with PREEMPT but not RT.
I rebuilt it and replaced the file under "releases", please re-download.
```
$ uname -a
Linux jambox 5.4.81-rt45-v8+ #9 SMP PREEMPT_RT Mon Dec 28 00:13:29 PST 2020 aarch64 GNU/Linux
```
FYI with the RT patch set enabled, the 5.4 kernel works fine on Pi4 but will not  boot on Pi3.
