### ISSUE TITLE
Kernel not working on Ubuntu MATE

### ISSUE THREAD

**Issue by nikaulen** [kdoren/linux#15]
Hi, 

I'm not sure whether this is the right place to ask this, so feel free to close the issue if I'm in the wrong place. 

I have managed to install a RT kernel on Raspberry Pi OS Lite 32 bit but I need to get the rt kernel running on any Ubuntu RPi OS version (tried on Ubuntu MATE 20.04.1 and Ubuntu Server 20.04.3 LTS). However, following the instructions of your RT kernel releases leads my RPi 4B 8GB to rainbow screen or not booting whatsoever. 
Is this supposed to work equally on Ubuntu systems? Or could you maybe give me some pointers on how to get an RT kernel running on RPi Ubuntu?

Some help would be greatly appreciated. And please excuse if I'm missing something obvious, I'm pretty new to the Linux/RPi world. 

Thanks and best regards

**Comment by kdoren** [comment]
@nikaulen I started a wiki and wrote up an install procedure for Ubuntu, which has some differences.

I tested with 32-bit Ubuntu Server 20.04.3 LTS and Ubuntu Server 21.04

https://github.com/kdoren/linux/wiki/Installation-of-kernel-from-deb-package-(Ubuntu)

I should add that by "tested" I mean a smoke test - it boots and appears functional.  I didn't test beyond that.
Please report back with your results.

**Comment by nikaulen** [comment]
@kdoren Thank you very much for the quick and easy instructions to do this! Your instructions worked for me on a 64-bit Ubuntu Server 20.04.03 LTS install. I haven't encountered any issues so far, although I didn't test audio functionality as it isn't relevant for me. I'll post here if I encounter anything noteworthy. Thanks again!
