### ISSUE TITLE
Kernel with HiFiBerry DAC+ADC Pro Updates

### ISSUE THREAD

**Issue by mesheets** [kdoren/linux#17]
A [pull request updating support for the HiFiBerry DAC+ADC Pro](https://github.com/raspberrypi/linux/pull/4618/commits) was recently accepted into [RaspberryPi/Linux](https://github.com/raspberrypi/linux).  Would like to request that this be included in the next PREEMPT_RT kernel release.

**Comment by kdoren** [comment]
Yes I did notice that (and I have one of those boards).

I build PREEMPT_RT kernel starting from paspberrypi/linux merge commit from upstream linux.  That includes everything accepted into raspberrypi/linux up until that point.  So the HiFiBerry commits will be in next PREEMPT_RT release.

I typically make builds of PREEMPT_RT when there is a release of the PREEMPT_RT patch set that matches a merge commit to raspberrypi/linux.  Neither one tracks every minor release, so there's no telling when that might be.  Could be 3 days from now or 3 months from now.   If you're in a hurry you could try building your own (see my wiki in this repo) but there is some small risk in using a patch set from a different kernel version.

**Comment by mesheets** [comment]
Thank you, that sounds fine.

My understanding is also that these updates additionally integrate support for the HiFiBerry DAC+ ADC Stage ([product page](https://www.hifiberry.com/shop/development-kits/dac-adc-stage-development-kit/) | [datasheet](https://www.hifiberry.com/docs/data-sheets/datasheet-dac-adc-stage/)).  Though both those HiFiBerry links note the Stage isn't currently being sold to end users, it is part of the Symonics Fastmusic Box Pro ([DIY kit](https://symonics.com/product/fastmusic-box-pro-diy-kit/) | [prebuilt plus with bundled Fastmusic Box OS license](https://symonics.com/product/fastmusic-box-pro/)).

**Comment by kdoren** [comment]
The HiFiBerry updates are included in release 5.10.73
