### ISSUE TITLE
5.10.73-rt54-v7l+ doesn't boot on RPi3

### ISSUE THREAD

**Issue by LPrenzel** [kdoren/linux#18]
Using a fresh Rasperry Pi OS Lite install on a Raspberry Pi 3B+, `5.10.73-rt54-v7l+` does not boot when following the instructions to install from `.deb`. Since it's headless I can't tell the exact cause. Following the same steps with `5.10.59-rt51-v7l+` works out-of-the-box.

Thanks for all the work, it's great to have easy access to the preempt patch!

**Comment by kdoren** [comment]
@LPrenzel Thanks for reporting.  It boots on Pi4 but I just tried a Pi3 and it failed to boot.  In the past that has meant that some additional patch was required.  I'll look into it.

**Comment by kdoren** [comment]
There were problems with the raspberrypi/linux repo which have since been fixed.  Doesn't appear to be rt-specific.
I was able to make a build from newer sources that works on Pi3.  I'll post a new release soon.

**Comment by LPrenzel** [comment]
Thanks a lot!

**Comment by kdoren** [comment]
@LPrenzel I just posted release 5.10.74-rt54 which boots for me on pi3.  Please give it a try and report your results.

**Comment by LPrenzel** [comment]
@kdoren Tried it out and it works. Thanks a lot!

**Comment by git-aniket** [comment]
hi @kdoren ,
First of all thank you for the nice work.

I was trying to get PREEMPT_RT working on my raspberry pi3Bv 1.2(raspbian 32 bit) using the .deb files provided in the link
https://github.com/kdoren/linux/releases/tag/rpi_5.15.65-rt49
while following the wiki:
https://github.com/kdoren/linux/wiki/Installation-of-kernel-from-deb-package-%28Raspberry-Pi-OS%29

The installation went fine.
However, when I reboot my system, I still see no PREEMPT_RT on the output of 'uname -a'

My uname command returns:
Linux pi3Bnew 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux

I see that my kernel is not exactly 5.15.65.  

Could you please let me know if this is the reason why PREEMPT_RT is not active?

Thank you in advance.

---------------------------------------------------------------------------------------------------------------------------------


Some more system info:

root@pi3Bnew:/home/pi/kernel# raspinfo
System Information
------------------

Raspberry Pi 3 Model B Rev 1.2
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"

Raspberry Pi reference 2022-04-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 226b479f8d32919c9fe36dd5b4c20c02682f8180, stage4

Linux pi3Bnew 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux
Revision        : a02082
Serial          : 000000008364e135
Model           : Raspberry Pi 3 Model B Rev 1.2
Throttled flag  : throttled=0x50005
Camera          : supported=0 detected=0, libcamera interfaces=0

Videocore information
---------------------

Aug 26 2022 14:04:36
Copyright (c) 2012 Broadcom
version 102f1e848393c2112206fadffaaf86db04e98326 (clean) (release) (start)

alloc failures:     0
compactions:        0
legacy block fails: 0

Filesystem information
----------------------
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       61225032 5896488  52786712  11% /
devtmpfs          439048       0    439048   0% /dev
tmpfs             472328       0    472328   0% /dev/shm
tmpfs             188932     960    187972   1% /run
tmpfs               5120       4      5116   1% /run/lock
/dev/mmcblk0p1    258095   75746    182349  30% /boot
tmpfs              94464      20     94444   1% /run/user/1000
