### ISSUE TITLE
Installing only the header package results in Setting up linux-libc-dev

### ISSUE THREAD

**Issue by guysoft** [kdoren/linux#22]
**Is this the right place for my bug report?**

**Describe the bug**
When installing only the linux header package, it assumes the linux image pacakges is there and fails.

**To reproduce**
1. Make sure linux-image is not installed.
2. 
```
dpkg -i linux-headers-5.10.74-rt54-v7l+_5.10.74-1_armhf.deb linux-libc-dev_5.10.74-1_armhf.deb
```

**Expected behaviour**
Should mkdir -p the image folder, or have an if statement if the folder exists before trying to run cp.

**Actual behaviour**
```
+ dpkg -i linux-headers-5.10.74-rt54-v7l+_5.10.74-1_armhf.deb linux-libc-dev_5.10.74-1_armhf.deb
Selecting previously unselected package linux-headers-5.10.74-rt54-v7l+.
(Reading database ... 41527 files and directories currently installed.)
Preparing to unpack linux-headers-5.10.74-rt54-v7l+_5.10.74-1_armhf.deb ...
Unpacking linux-headers-5.10.74-rt54-v7l+ (5.10.74-1) ...
dpkg: warning: downgrading linux-libc-dev:armhf from 1:1.20220120-1 to 5.10.74-1
Preparing to unpack linux-libc-dev_5.10.74-1_armhf.deb ...
Unpacking linux-libc-dev:armhf (5.10.74-1) over (1:1.20220120-1) ...
Setting up linux-headers-5.10.74-rt54-v7l+ (5.10.74-1) ...
Setting up linux-libc-dev:armhf (5.10.74-1) ...
+ KERN=5.10.74-rt54-v7l+
+ mkdir -p /boot/5.10.74-rt54-v7l+/overlays/
+ cp -d '/usr/lib/linux-image-5.10.74-rt54-v7l+/overlays/*' /boot/5.10.74-rt54-v7l+/overlays/
cp: cannot stat '/usr/lib/linux-image-5.10.74-rt54-v7l+/overlays/*': No such file or directory
++++ echo_red 'build failed, unmounting image...'
```

**System**

Its a CustomPiOS build for RealtimePi

**Additional context**
it does not effect me, but I though its worth reporting. You can close if ``wontfix``

**Comment by kdoren** [comment]
@guysoft The failed step is after the deb packages are installed.
You can install only the header packages.  
But if you don't install linux-image, you can't copy the linux-image files.

> To reproduce
> Make sure linux-image is not installed.

Installing linux-image is what places files in /usr/lib/linux-image-5.10.74-rt54-v7l+/overlays/  
So the install script will always fail if linix-image is not installed. 

```
+ cp -d '/usr/lib/linux-image-5.10.74-rt54-v7l+/overlays/*' /boot/5.10.74-rt54-v7l+/overlays/
cp: cannot stat '/usr/lib/linux-image-5.10.74-rt54-v7l+/overlays/*': No such file or directory
```

See:
https://github.com/kdoren/linux/wiki/Installation-of-kernel-from-deb-package-%28Raspberry-Pi-OS%29

**Comment by guysoft** [comment]
Ok, so can be closed I guess

**Comment by kdoren** [comment]
@guysoft FYI installing the linux-image deb package merely places the files in /usr/lib/$KERN/.  It doesn't make the kernel active.  So there is no reason to install the headers but not the image.

Then my install process copies the files to /boot/5.10.74-rt54-v7l+/,   That doesn't make the kernel active either.

The thing that makes the kernel active is the section in /boot/config.txt that sets the parameters used to boot (kernel, os_prefix, and overlay_prefix).  My install process has that section set to [all] at the top, but if you have multiple kernels installed, just change [all] to [none] above the kernels you don't want to boot.  Only set [all] above the section for the kernel you want to boot.

**Comment by guysoft** [comment]
Indeed I do that here:
https://github.com/guysoft/RealtimePi/blob/devel/src/modules/realtimepi/start_chroot_script#L27
