### ISSUE TITLE
Latest release does not work for new RPI4

### ISSUE THREAD

**Issue by HomicidalBrainiac** [kdoren/linux#36]
### Describe the bug

I recently purchased a RPI4B, followed your directions to install the .deb according to your instructions, of course taking into account config.txt is at /boot/firmware/config.txt

The system starts, gets to the raspberry PI OS loading screen, then a blank screen and cursor.

### Steps to reproduce the behaviour

install .deb on new RPI4 as instructed on the github repo.  

### Device (s)

Raspberry Pi 4 Mod. B

### System

Latest bookworm release, 64 bit OS, Kernel 6.6.31

### Logs

unable

**Comment by HomicidalBrainiac** [comment]
Wait, I just realized that the Kernel is also stored in /boot/firmware and not /boot.  I think you might want to update your instructions to account for the new directory structure RPI uses.

**Comment by kdoren** [comment]
@HomicidalBrainiac  Thanks for reporting.   

I just tried it on a Pi4 and it worked.   I downloaded latest bookworm 64-bit raspbery pi OS (plus updates).  Then installed 64-bit kernel-image 6.6.35-rt34-rpi-v8+ from releases.

```
# as root:
apt update
apt upgrade
reboot
apt install ./linux-image-6.6.35-rt34-rpi-v8+_6.6.35-1_arm64.deb
export KERN=6.6.35-rt34-rpi-v8+
# then copy/paste block of code from wiki, and review /boot/firmware/config.txt
```

I copied and pasted the block of code from the wiki, reviewed /boot/firmware/config,txt but did not make changes, then rebooted into PREEMPT_RT kernel.  This block of code is designed to use /boot/firmware/ if it exists.

```
root@raspberrypi:/home/pi# uname -r
6.6.35-rt34-rpi-v8+
```

So why did it not work for you?  I'm not sure, but one theory is that maybe older firmware on your Pi4 might not play nice with the newer /boot/firmware directory structure.

-Kevin

**Comment by HomicidalBrainiac** [comment]
Yes, the issue is solved.  I have it working and I truly appreciate the work you’ve done!In my case, I got it working just by manually cutting and pasting line by line over ssh. Sent from my iPhoneOn Aug 21, 2024, at 5:54 PM, Kevin Doren ***@***.***> wrote:﻿
@HomicidalBrainiac  Thanks for reporting.
I just tried it on a Pi4 and it worked.   I downloaded latest bookworm 64-bit raspbery pi OS (plus updates).  Then installed 64-bit kernel-image 6.6.35-rt34-rpi-v8+ from releases.
# as root:
apt update
apt upgrade
reboot
apt install ./linux-image-6.6.35-rt34-rpi-v8+_6.6.35-1_arm64.deb
export KERN=6.6.35-rt34-rpi-v8+
# then copy/paste block of code from wiki, and review /boot/firmware/config.txt

I copied and pasted the block of code from the wiki, reviewed /boot/firmware/config,txt but did not make changes, then rebooted into PREEMPT_RT kernel.  This block of code is designed to use /boot/firmware/ if it exists.
***@***.***:/home/pi# uname -r
6.6.35-rt34-rpi-v8+

So why did it not work for you?  I'm not sure, but one theory is that maybe older firmware on your Pi4 might not play nice with the newer /boot/firmware directory structure.
-Kevin

**Comment by kdoren** [comment]
@HomicidalBrainiac I'm glad you got it working.  FYI, you should be able to simply copy and paste the entire block of code from the Wiki page, then hit enter.  It should not be necessary to do it line-by-line.
