### ISSUE TITLE
Installation description for 5.10.16-rt30 kernel

### ISSUE THREAD

**Issue by Mohawi** [kdoren/linux#4]
Following the installation steps proposed for installing the kernel from the prebuild .tgz file bricks the device. The steps propose to copy the kernel image twice. Non of the steps copies the provided *.dtb file to the boot directory.
Please fix the installation manual.

Also: the three provided .deb files do not seem to work. I tried to install the kernel by installing all three of them. Since it didn't work I switched to the .tgz file.

**Comment by Mohawi** [comment]
Besides that, many many thanks for providing those up to date rt kernels. You're a hero 👍

**Comment by kdoren** [comment]
@Mohawi Thanks for reporting.

I fixed the instructions for installing from tgz file, so the instructions should work now.
I tried installing from deb package; that also seems to work, but requires lines in /boot/config.txt to use it.

**Comment by Mohawi** [comment]
Ah ok, I wasn't aware of the need to modify the /boot/config.txt after installing the .deb files. 
Thanks.
