### ISSUE TITLE
working arm64 RT v5 kernel for RPi3?

### ISSUE THREAD

**Issue by gnulabis** [kdoren/linux#6]
Hi, just a quick question, have you found any v5 kernel commit + RT patch combination that gives you a working arm64 RT kernel for RPi3? I've been trying several combinations but no luck so far.

Thanks!

**Comment by kdoren** [comment]
I haven't tried recently, but 5.4 64-bit PREEMPT_RT kernel (under "releases") would not even boot on Pi3.
I tried 5.10 32-bit PREEMPT_RT kernel on Pi3 (also under "releases"), and it boots, but hangs in rt_throttling when you run jack audio.
So I have been running PREEMPT (low-latency, not _RT) kernel on Pi3.

**Comment by gnulabis** [comment]
ok, thanks for the feedback

**Comment by woodz-** [comment]
Is there a deep technical explanation on why it isn't possible to get a 64bit kernel to run on an rpi3 for multiple years?
